# seed_challenges.py

from app import create_app, db
from app.models import Challenge

def seed_database():
    app = create_app()
    with app.app_context():
        # reset database
        db.drop_all()
        db.create_all()

        challenges = [
            # --- EASY (90 × regen_hours=6) ---
            {"title":"Inbox March","description":"march in place while clearing 10 emails (7 min)","difficulty":"E","points":60},
            {"title":"Stair‑tune","description":"sing your favorite song on the stairs (5 min)","difficulty":"E","points":70},
            {"title":"Plant Patrol","description":"water 3 plants, pacing between each (8 min)","difficulty":"E","points":50},
            {"title":"Sock Slide","description":"slide in socks across a floor, return ×10 (10 reps)","difficulty":"E","points":80},
            {"title":"Desk Tap","description":"tap feet alternately under desk (10 min)","difficulty":"E","points":40},
            {"title":"Posture Reset","description":"10× shoulder‑blade squeezes (10 reps)","difficulty":"E","points":30},
            {"title":"Book Balance","description":"hold a book on head & walk back and forth (5 min)","difficulty":"E","points":55},
            {"title":"Window Watch","description":"pace reading campus news board (7 min)","difficulty":"E","points":45},
            {"title":"Coffee Stroll","description":"sip & stroll (5 min)","difficulty":"E","points":50},
            {"title":"Mirror Moves","description":"copy your reflection’s stretch (6 min)","difficulty":"E","points":35},
            {"title":"Corridor Karaoke","description":"sing & stroll (2 min)","difficulty":"E","points":100},
            {"title":"Hallway Hop","description":"skip 10 steps down a corridor (10 reps)","difficulty":"E","points":70},
            {"title":"Fruit & Stroll","description":"eat an apple then stroll (5 min)","difficulty":"E","points":25},
            {"title":"Leg Shake","description":"shake each leg 1 min while seated (2 min)","difficulty":"E","points":20},
            {"title":"Arm Circles","description":"1 min of arm circles waiting for class","difficulty":"E","points":20},
            {"title":"Posture Pause","description":"stand & roll shoulders every 10 min for 5 min","difficulty":"E","points":20},
            {"title":"Snack Fetch","description":"walk to vending machine & back (4 min)","difficulty":"E","points":15},
            {"title":"Gratitude Walk","description":"name 3 things you’re grateful for while walking (5 min)","difficulty":"E","points":60},
            {"title":"Cloud Count","description":"walk and count clouds (3 min)","difficulty":"E","points":30},
            {"title":"Leaf Collect","description":"gather 5 unique leaves on campus (8 min)","difficulty":"E","points":40},
            {"title":"Bench Balance","description":"stand on one leg at a bench (30 s each)","difficulty":"E","points":90},
            {"title":"Corridor Yoga","description":"do 3 yoga poses in hallway (5 min)","difficulty":"E","points":75},
            {"title":"Campus Loop","description":"one circuit around the quad (7 min)","difficulty":"E","points":55},
            {"title":"Text & Trek","description":"walk 2 min while texting safely","difficulty":"E","points":20},
            {"title":"Shoe Swap","description":"walk barefoot on grass (5 min)","difficulty":"E","points":65},
            {"title":"Water Break","description":"drink 2 glasses, pace for 2 min","difficulty":"E","points":30},
            {"title":"Brain Break","description":"5 min mindful walk","difficulty":"E","points":40},
            {"title":"Calf Raises","description":"15 reps during study break","difficulty":"E","points":60},
            {"title":"Wrist Rolls","description":"2 min of wrist rotations","difficulty":"E","points":20},
            {"title":"Seated Twist","description":"2 min twisting stretch","difficulty":"E","points":25},
            {"title":"Quick Jacks","description":"jumping jacks for 1 min","difficulty":"E","points":100},
            {"title":"Wall Sit","description":"30 s hold","difficulty":"E","points":110},
            {"title":"Shoulder Rolls","description":"30 s forward/back","difficulty":"E","points":20},
            {"title":"Neck Stretches","description":"2 min","difficulty":"E","points":20},
            {"title":"Hip Circles","description":"2 min","difficulty":"E","points":30},
            {"title":"Toe Touches","description":"1 min bending stretch","difficulty":"E","points":20},
            {"title":"Ankle Pumps","description":"2 min","difficulty":"E","points":20},
            {"title":"Seated Leg Lifts","description":"15 reps per leg","difficulty":"E","points":35},
            {"title":"Mini‑Plank","description":"30 s hold","difficulty":"E","points":90},
            {"title":"Side‑Leg Raises","description":"15 reps per side","difficulty":"E","points":80},
            {"title":"Cloud Stretch","description":"reach for clouds—stretch & sway (2 min)","difficulty":"E","points":20},
            {"title":"Pet Patrol","description":"visit campus animal area & wander (5 min)","difficulty":"E","points":65},
            {"title":"Reflection Walk","description":"pace while journaling thoughts (3 min)","difficulty":"E","points":25},
            {"title":"Garden Gaze","description":"walk through garden & smell flowers (5 min)","difficulty":"E","points":35},
            {"title":"Chalk Doodle","description":"draw sidewalk doodle, then circle it (5 min)","difficulty":"E","points":55},
            {"title":"Stair Landing Dance","description":"dance at stair landing (2 min)","difficulty":"E","points":80},
            {"title":"Phone‑Free Walk","description":"5 min without phone noticing details","difficulty":"E","points":55},
            {"title":"Backpack Carry","description":"walk 5 min with a loaded backpack","difficulty":"E","points":60},
            {"title":"Poster Pace","description":"walk and read all posters on a wall (5 min)","difficulty":"E","points":35},
            {"title":"Silent Disco","description":"walk dancing 5 min with headphones","difficulty":"E","points":70},
            {"title":"Balance Book","description":"balance a book on head and walk in circle (3 min)","difficulty":"E","points":45},
            {"title":"Shadow Steps","description":"mimic your shadow while walking (4 min)","difficulty":"E","points":50},
            {"title":"Balloon Bounce","description":"keep a balloon in air using head only (2 min)","difficulty":"E","points":65},
            {"title":"Finger Flicks","description":"flick each finger 10× while standing","difficulty":"E","points":25},
            {"title":"Desk Yoga","description":"3 chair yoga poses (5 min)","difficulty":"E","points":50},
            {"title":"Window Tap","description":"tap window with alternating hands (3 min)","difficulty":"E","points":20},
            {"title":"Walk & Talk","description":"pace while on a 5‑min call","difficulty":"E","points":60},
            {"title":"Pencil Balance","description":"balance pencil on finger & walk (3 min)","difficulty":"E","points":30},
            {"title":"Shoe Shuffle","description":"shuffle feet in place (3 min)","difficulty":"E","points":20},
            {"title":"Mini‑Lunge","description":"10 lunges per leg","difficulty":"E","points":75},
            {"title":"Notebook Juggle","description":"toss notebook & catch while walking (2 min)","difficulty":"E","points":90},
            {"title":"Chair Dance","description":"stand & dance around chair (3 min)","difficulty":"E","points":80},
            {"title":"Hallway High‑Five","description":"high‑five 5 friends while walking (5 min)","difficulty":"E","points":60},
            {"title":"Bubble Pop Walk","description":"pop imaginary bubbles while strolling (4 min)","difficulty":"E","points":30},
            {"title":"Desk Push‑ups","description":"10 incline push‑ups on desk","difficulty":"E","points":70},
            {"title":"Leg Cross Stretch","description":"cross one leg over knee & lean (2 min)","difficulty":"E","points":30},
            {"title":"Drink & Drift","description":"sip water while drifting side to side (3 min)","difficulty":"E","points":20},
            {"title":"Wall Clap","description":"clap hands overhead leaning on wall (2 min)","difficulty":"E","points":20},
            {"title":"Stair Scribble","description":"draw on stair with chalk then erase (5 min)","difficulty":"E","points":55},
            {"title":"Light Jog‑in‑Place","description":"jog for 1 min","difficulty":"E","points":90},
            {"title":"Phone Plank","description":"hold plank while reading phone text (30 s)","difficulty":"E","points":90},
            {"title":"Book Push","description":"push book across table with nose then walk (3 min)","difficulty":"E","points":45},
            {"title":"Window Clean March","description":"march while cleaning window (5 min)","difficulty":"E","points":60},
            {"title":"Backpack Squats","description":"squat 10× with backpack","difficulty":"E","points":80},
            {"title":"Corridor Leap","description":"leap forward 5×","difficulty":"E","points":50},
            {"title":"Tiptoe Transit","description":"walk on tiptoes for 2 min","difficulty":"E","points":45},
            {"title":"Sideways Shuffle","description":"shuffle sideways down hallway (3 min)","difficulty":"E","points":40},
            {"title":"Bookcase Reach","description":"reach top shelf then squat (5 reps)","difficulty":"E","points":30},
            {"title":"Mailbox Run","description":"run to mailbox & back (2 min)","difficulty":"E","points":60},
            {"title":"Plant Stretch","description":"stretch arms overhead then bend (2 min)","difficulty":"E","points":20},
            {"title":"Sit‑to‑Stand","description":"stand up & sit down slowly 10×","difficulty":"E","points":70},
            {"title":"Selfie Walk","description":"take 5 selfies at different spots (5 min)","difficulty":"E","points":55},
            {"title":"Chalk Jump","description":"jump over chalk line 10×","difficulty":"E","points":60},
            {"title":"Chair Spin","description":"sit & spin 5× then walk (3 min)","difficulty":"E","points":40},
            {"title":"Puddle Jump","description":"jump over small puddles 5×","difficulty":"E","points":20},
            {"title":"Snack Balance","description":"balance snack on head then eat (3 min)","difficulty":"E","points":30},
            {"title":"Mirror Stretch","description":"mirror someone else’s stretch (2 min)","difficulty":"E","points":20},
            {"title":"Earbud Dance","description":"dance with one earbud in (3 min)","difficulty":"E","points":35},
            {"title":"Tile Tap","description":"tap each floor tile with foot (2 min)","difficulty":"E","points":20},
            {"title":"Ink Walk","description":"walk while doodling on paper (5 min)","difficulty":"E","points":50},

            # --- MEDIUM (60 × regen_hours=8) ---
            {"title":"Café Crawl","description":"walk to 3 cafés—15 min","difficulty":"M","points":140},
            {"title":"Chalk Artist","description":"draw & admire sidewalk art—20 min","difficulty":"M","points":155},
            {"title":"Tree Hug Relay","description":"hug 5 trees, walk between them—20 min","difficulty":"M","points":130},
            {"title":"Yoga in Park","description":"follow 25 min video outside","difficulty":"M","points":210},
            {"title":"Flash‑Mob Prep","description":"learn 3 steps & practice—30 min","difficulty":"M","points":220},
            {"title":"Partner Stretch","description":"partner‑assisted stretch—15 min","difficulty":"M","points":160},
            {"title":"Memory Lane Walk","description":"revisit 3 old campus spots—20 min","difficulty":"M","points":150},
            {"title":"Graffiti Tour","description":"photo 5 street‑art spots—20 min","difficulty":"M","points":145},
            {"title":"Staircase Sweep","description":"sweep one stairwell—15 min","difficulty":"M","points":175},
            {"title":"Sidewalk Picnic","description":"walk to spot, eat, walk back—20 min","difficulty":"M","points":140},
            {"title":"Pet Walk","description":"walk a friend’s pet—15 min","difficulty":"M","points":200},
            {"title":"Trail Tease","description":"nature‑trail wander—20 min","difficulty":"M","points":200},
            {"title":"Resistance Band Flow","description":"band exercises—15 min","difficulty":"M","points":135},
            {"title":"Garden Care","description":"15 min gardening—15 min","difficulty":"M","points":190},
            {"title":"Outdoor Photo Walk","description":"explore & shoot—20 min","difficulty":"M","points":125},
            {"title":"Frisbee Fun","description":"toss & walk—20 min","difficulty":"M","points":135},
            {"title":"Staircase Dance","description":"dance on stairs—5 min","difficulty":"M","points":155},
            {"title":"Mall Walk","description":"indoor mall stroll—15 min","difficulty":"M","points":145},
            {"title":"Park Bench Chat","description":"stroll & chat—15 min","difficulty":"M","points":160},
            {"title":"Window Wash","description":"clean one window standing up—15 min","difficulty":"M","points":135},
            {"title":"Campus Cleanup","description":"pick up litter—15 min","difficulty":"M","points":230},
            {"title":"Song & Stroll","description":"new playlist walk—10 min","difficulty":"M","points":165},
            {"title":"Scooter Ride","description":"ride scooter—15 min","difficulty":"M","points":195},
            {"title":"Dance Class Sampler","description":"online tutorial—15 min","difficulty":"M","points":200},
            {"title":"Stair Climb","description":"climb 10 floors—15 min","difficulty":"M","points":190},
            {"title":"Playground Games","description":"play tag—10 min","difficulty":"M","points":150},
            {"title":"Medicine‑ball Throws","description":"10 reps","difficulty":"M","points":180},
            {"title":"Shadow Boxing","description":"10 min","difficulty":"M","points":170},
            {"title":"Mall Window Shop","description":"browse windows—20 min","difficulty":"M","points":150},
            {"title":"Campus Mural Tour","description":"view 5 murals—20 min","difficulty":"M","points":155},
            {"title":"Birdwatch Stroll","description":"spot 5 birds—20 min","difficulty":"M","points":140},
            {"title":"Chess & Walk","description":"move piece then walk—20 min","difficulty":"M","points":130},
            {"title":"Photo Scavenger","description":"find & photograph 5 items—25 min","difficulty":"M","points":180},
            {"title":"Stair‑step Beats","description":"step to music—15 min","difficulty":"M","points":160},
            {"title":"Coin Balance Walk","description":"balance coin on head—15 min","difficulty":"M","points":130},
            {"title":"Yoga Circle","description":"join group yoga—20 min","difficulty":"M","points":210},
            {"title":"Sketch & Stretch","description":"draw then stretch—20 min","difficulty":"M","points":170},
            {"title":"Tree Sit","description":"sit in tree then climb down—15 min","difficulty":"M","points":140},
            {"title":"Parkour Basics","description":"practice simple moves—15 min","difficulty":"M","points":160},
            {"title":"Lab Tour","description":"walk through labs & note—20 min","difficulty":"M","points":145},
            {"title":"Staircase Photo","description":"artistic stair photo—20 min","difficulty":"M","points":150},
            {"title":"Poetry Walk","description":"read poem then walk—15 min","difficulty":"M","points":130},
            {"title":"Sun Salutation","description":"15 min yoga sequence","difficulty":"M","points":200},
            {"title":"Bandstand Dance","description":"dance at bandstand—15 min","difficulty":"M","points":180},
            {"title":"Chalk Messages","description":"write & walk—20 min","difficulty":"M","points":155},
            {"title":"Reflex Walk","description":"catch tossed ball while walking—15 min","difficulty":"M","points":170},
            {"title":"Quiz Trail","description":"answer quiz at stops—20 min","difficulty":"M","points":185},
            {"title":"Bike Errand","description":"bike to run errand—20 min","difficulty":"M","points":195},
            {"title":"Staircase Reading","description":"read & step—15 min","difficulty":"M","points":140},
            {"title":"Flower Sketch","description":"sketch flowers then walk—20 min","difficulty":"M","points":145},
            {"title":"Dance Tag","description":"tag friend & dance 20 s then walk—15 min","difficulty":"M","points":150},
            {"title":"Yoga Duo","description":"partner yoga—20 min","difficulty":"M","points":200},
            {"title":"Hopscotch Chalk","description":"draw & play—15 min","difficulty":"M","points":170},
            {"title":"Blindfold Walk","description":"guided blindfold walk—10 min","difficulty":"M","points":180},
            {"title":"Sound Hunt","description":"identify 5 sounds—20 min","difficulty":"M","points":130},
            {"title":"Stair Plank","description":"plank on stairs 2×1 min—10 min","difficulty":"M","points":160},
            {"title":"Wall‑Sit Read","description":"wall sit while reading—10 min","difficulty":"M","points":150},
            {"title":"Photo Recreation","description":"recreate old campus photo—25 min","difficulty":"M","points":180},
            {"title":"Lab Experiment Walk","description":"mini‑test then walk—20 min","difficulty":"M","points":190},
            {"title":"Group Walk & Talk","description":"with 2 friends—20 min","difficulty":"M","points":160},

            # --- HARD (30 × regen_hours=10) ---
            {"title":"Sunrise Yoga Series","description":"50 min outdoors","difficulty":"H","points":330},
            {"title":"Urban Photo Marathon","description":"10 photo spots—60 min","difficulty":"H","points":350},
            {"title":"1‑Mile Fun Run","description":"≈10 min run + warm‑up","difficulty":"H","points":400},
            {"title":"Dance‑Yoga Fusion","description":"flow & freestyle—45 min","difficulty":"H","points":320},
            {"title":"Community Garden Build","description":"1 h of work & walk","difficulty":"H","points":340},
            {"title":"Campus Relay Race","description":"organize & complete—60 min","difficulty":"H","points":320},
            {"title":"Scooter Tour","description":"1 h exploring campus","difficulty":"H","points":270},
            {"title":"Paddleboard Weekend","description":"1 h/day×2 days","difficulty":"H","points":400},
            {"title":"3‑Day Sunrise Walk","description":"20 min/day—60 min total","difficulty":"H","points":300},
            {"title":"Backpack Hike","description":"3 days×15 min/day—45 min total","difficulty":"H","points":310},
            {"title":"Stair‑Only Commute","description":"2 days×45 min/day—90 min total","difficulty":"H","points":280},
            {"title":"Flash Mob Performance","description":"plan & perform—60 min","difficulty":"H","points":380},
            {"title":"Parkour Workshop","description":"1 h session","difficulty":"H","points":360},
            {"title":"Bicycle Scavenger","description":"5 stops in 1 h","difficulty":"H","points":300},
            {"title":"Dance Workshop","description":"learn routine—1 h","difficulty":"H","points":350},
            {"title":"Campus Triathlon","description":"swim/bike/run—1 h total","difficulty":"H","points":390},
            {"title":"5×5 Plank Series","description":"5 planks×1 min—5 min total","difficulty":"H","points":260},
            {"title":"Garden Marathon","description":"weed & walk—1 h","difficulty":"H","points":330},
            {"title":"Story Walk","description":"read chapters while walking—1 h","difficulty":"H","points":340},
            {"title":"Campus Climb","description":"climb tallest stair 10×—1 h","difficulty":"H","points":300},
            {"title":"Host Flash Mob","description":"host & dance—1 h","difficulty":"H","points":380},
            {"title":"Photo Story","description":"create photo story—1 h","difficulty":"H","points":350},
            {"title":"Yoga Marathon","description":"5×10 min sessions—50 min","difficulty":"H","points":330},
            {"title":"Community Clean‑up","description":"1 h + stroll","difficulty":"H","points":340},
            {"title":"2‑Day Bike Tour","description":"30 min/day—60 min total","difficulty":"H","points":310},
            {"title":"Sunrise‑to‑Sunset Walk","description":"60 min continuous","difficulty":"H","points":370},
            {"title":"History Tour","description":"guide group 1 h","difficulty":"H","points":360},
            {"title":"Obstacle Course","description":"build & run—1 h","difficulty":"H","points":400},
            {"title":"Chalk Festival","description":"draw & wander 3×20 min—60 min","difficulty":"H","points":350},
            {"title":"Silent Disco Host","description":"DJ & dance—1 h","difficulty":"H","points":380},
        ]

        # insert with correct regen_hours
        for c in challenges:
            regen = 6 if c["difficulty"]=="E" else 8 if c["difficulty"]=="M" else 10
            db.session.add(Challenge(
                title=c["title"],
                description=c["description"],
                difficulty=c["difficulty"],
                points=c["points"],
                regen_hours=regen
            ))

        db.session.commit()
        print("Successfully seeded 180 challenges.")

if __name__ == "__main__":
    seed_database()
