import json
import os
import sys

# Add parent directory to path so we can import from app
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Define challenges data
challenges = [
    # --- EASY (90 × regen_hours=4) ---
    {"title":"Inbox March","description":"march in place while clearing 10 emails (7 min)","difficulty":"E","points":60},
    {"title":"Stair‑tune","description":"sing your favorite song on the stairs (5 min)","difficulty":"E","points":70},
    {"title":"Plant Patrol","description":"water 3 plants, pacing between each (8 min)","difficulty":"E","points":50},
    {"title":"Sock Slide","description":"slide in socks across a floor, return ×10 (10 reps)","difficulty":"E","points":80},
    {"title":"Desk Tap","description":"tap feet alternately under desk (10 min)","difficulty":"E","points":40},
    {"title":"Posture Reset","description":"10× shoulder‑blade squeezes (10 reps)","difficulty":"E","points":30},
    {"title":"Book Balance","description":"hold a book on head & walk back and forth (5 min)","difficulty":"E","points":55},
    {"title":"Window Watch","description":"pace reading campus news board (7 min)","difficulty":"E","points":45},
    {"title":"Coffee Stroll","description":"sip & stroll (5 min)","difficulty":"E","points":50},
    {"title":"Corridor Karaoke","description":"sing & stroll (2 min)","difficulty":"E","points":100},
    {"title":"Hallway Hop","description":"skip 10 steps down a corridor (10 reps)","difficulty":"E","points":70},
    {"title":"Fruit & Stroll","description":"eat an apple then stroll (5 min)","difficulty":"E","points":25},
    {"title":"Leg Shake","description":"shake each leg 1 min while seated (2 min)","difficulty":"E","points":20},
    {"title":"Arm Circles","description":"1 min of arm circles waiting for class","difficulty":"E","points":20},
    {"title":"Snack Fetch","description":"walk to vending machine & back (4 min)","difficulty":"E","points":15},
    {"title":"Gratitude Walk","description":"name 3 things you're grateful for while walking (5 min)","difficulty":"E","points":60},
    {"title":"Cloud Count","description":"walk and count clouds (3 min)","difficulty":"E","points":30},
    {"title":"Leaf Collect","description":"gather 5 unique leaves on campus (8 min)","difficulty":"E","points":40},
    {"title":"Bench Balance","description":"stand on one leg on a bench (30 s each)","difficulty":"E","points":90},
    {"title":"Corridor Yoga","description":"do 3 yoga poses in hallway (5 min)","difficulty":"E","points":75},
    {"title":"Campus Loop","description":"walk a circle around the quad (7 min)","difficulty":"E","points":55},
    {"title":"Text & Trek","description":"walk 2 min while texting safely","difficulty":"E","points":20},
    {"title":"Shoe Swap","description":"walk barefoot on grass (5 min)","difficulty":"E","points":65},
    {"title":"Water Break","description":"drink 2 glasses, pace for 2 min","difficulty":"E","points":30},
    {"title":"Brain Break","description":"5 min mindful walk","difficulty":"E","points":40},
    {"title":"Calf Raises","description":"15 reps during study break","difficulty":"E","points":60},
    {"title":"Wrist Rolls","description":"2 min of wrist rotations","difficulty":"E","points":20},
    {"title":"Seated Twist","description":"2 min twisting stretch","difficulty":"E","points":25},
    {"title":"Quick Jacks","description":"jumping jacks for 1 min","difficulty":"E","points":100},
    {"title":"Wall Sit","description":"30 s hold","difficulty":"E","points":110},
    {"title":"Shoulder Rolls","description":"30 s forward/back","difficulty":"E","points":20},
    {"title":"Neck Stretches","description":"2 min","difficulty":"E","points":20},
    {"title":"Hip Circles","description":"2 min","difficulty":"E","points":30},
    {"title":"Toe Touches","description":"1 min bending stretch","difficulty":"E","points":20},
    {"title":"Ankle Pumps","description":"2 min","difficulty":"E","points":20},
    {"title":"Seated Leg Lifts","description":"15 reps per leg","difficulty":"E","points":35},
    {"title":"Mini‑Plank","description":"30 s hold","difficulty":"E","points":90},
    {"title":"Side‑Leg Raises","description":"15 reps per side","difficulty":"E","points":80},
    {"title":"Cloud Stretch","description":"reach for clouds—stretch & sway (2 min)","difficulty":"E","points":20},
    {"title":"Reflection Walk","description":"pace while journaling thoughts (3 min)","difficulty":"E","points":25},
    {"title":"Garden Gaze","description":"walk through garden & smell flowers (5 min)","difficulty":"E","points":35},
    {"title":"Chalk Doodle","description":"draw sidewalk doodle, then circle it (5 min)","difficulty":"E","points":55},
    {"title":"Stair Landing Dance","description":"dance at stair landing (2 min)","difficulty":"E","points":80},
    {"title":"Phone‑Free Walk","description":"5 min without phone noticing details","difficulty":"E","points":55},
    {"title":"Poster Pace","description":"walk and read all posters on a wall (5 min)","difficulty":"E","points":35},
    {"title":"Silent Disco","description":"walk dancing 5 min with headphones","difficulty":"E","points":70},
    {"title":"Balance Book","description":"balance a book on head and walk in circle (3 min)","difficulty":"E","points":45},
    {"title":"Shadow Steps","description":"mimic your shadow while walking (4 min)","difficulty":"E","points":50},
    {"title":"Balloon Bounce","description":"keep a balloon in air using head only (2 min)","difficulty":"E","points":65},
    {"title":"Desk Yoga","description":"3 chair yoga poses (5 min)","difficulty":"E","points":50},
    {"title":"Walk & Talk","description":"pace while on a 5‑min call","difficulty":"E","points":60},
    {"title":"Pencil Balance","description":"balance pencil on finger & walk (3 min)","difficulty":"E","points":30},
    {"title":"Shoe Shuffle","description":"shuffle feet in place (3 min)","difficulty":"E","points":20},
    {"title":"Mini‑Lunge","description":"10 lunges per leg","difficulty":"E","points":75},
    {"title":"Notebook Juggle","description":"toss notebook & catch while walking (2 min)","difficulty":"E","points":90},
    {"title":"Chair Dance","description":"stand & dance around chair (3 min)","difficulty":"E","points":80},
    {"title":"Hallway High‑Five","description":"high‑five 5 friends while walking (5 min)","difficulty":"E","points":60},
    {"title":"Bubble Pop Walk","description":"pop imaginary bubbles while strolling (4 min)","difficulty":"E","points":30},
    {"title":"Desk Push‑ups","description":"10 incline push‑ups on desk","difficulty":"E","points":70},
    {"title":"Leg Cross Stretch","description":"cross one leg over knee & lean (2 min)","difficulty":"E","points":30},
    {"title":"Wall Clap","description":"clap hands overhead leaning on wall (2 min)","difficulty":"E","points":20},
    {"title":"Light Jog‑in‑Place","description":"jog for 1 min","difficulty":"E","points":90},
    {"title":"Phone Plank","description":"hold plank while on phone (30 s)","difficulty":"E","points":90},
    {"title":"Book Push","description":"push book across table with nose then walk (3 min)","difficulty":"E","points":45},
    {"title":"Backpack Squats","description":"squat 10× with backpack","difficulty":"E","points":80},
    {"title":"Corridor Leap","description":"leap forward 5×","difficulty":"E","points":50},
    {"title":"Tiptoe Transit","description":"walk on tiptoes for 2 min","difficulty":"E","points":45},
    {"title":"Sideways Shuffle","description":"shuffle sideways down hallway (3 min)","difficulty":"E","points":40},
    {"title":"Plant Stretch","description":"stretch arms overhead then bend (2 min)","difficulty":"E","points":20},
    {"title":"Sit‑to‑Stand","description":"stand up & sit down slowly 10×","difficulty":"E","points":70},
    {"title":"Selfie Walk","description":"take 5 selfies at different spots (5 min)","difficulty":"E","points":55},
    {"title":"Chair Spin","description":"sit & spin 5× then walk (3 min)","difficulty":"E","points":40},
    {"title":"Puddle Jump","description":"jump over small puddles 5×","difficulty":"E","points":20},
    {"title":"Snack Balance","description":"balance snack on head then eat (3 min)","difficulty":"E","points":30},
    {"title":"Mirror Stretch","description":"mirror someone else's stretch (2 min)","difficulty":"E","points":20},
    {"title":"Ink Walk","description":"walk while doodling on paper (5 min)","difficulty":"E","points":50},
    {"title":"Furry Friends","description":"find and pet an animal(5 min)","difficulty":"E","points":50},
]
